version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        # 支持6、7、8、9、10、11六个版本
        jdkVersion: 8
        # 支持2.2.1、3.2.5、3.3.9、3.5.2、3.5.3、3.5.4、3.6.1、3.6.3八个版本
        mavenVersion: 3.3.9
        # 构建命令
        commands:
          - chmod +x ./java/langchain4j/linux/get_java_langchain4j_linux.sh && ./java/langchain4j/linux/get_java_langchain4j_linux.sh
  - stage:
    name: release
    displayName: 发布
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: '发布'
        # 上游上传制品任务的产出
        dependArtifact: output
        # 发布制品版本号
        version: '1.0.0.0'
        # 是否开启版本号自增，默认开启
        autoIncrement: true
triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - java/langchain4j/linux
