version: '1.0'
name: branch-pipeline
displayName: shell Pipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: shell@agent
        name: run linux shell
        displayName: linux shell
        # 构建命令
        script: |
          chmod +x ./java/langchain4j/linux/get_java_langchain4j_linux.sh 
          ./java/langchain4j/linux/get_java_langchain4j_linux.sh
triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - java/langchain4j/linux
