# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build elasticsearch

on:
  push:
    branches: [ "java/elasticsearch" ]
  pull_request:
    branches: [ "java/elasticsearch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: get_elasticsearch
        run:  |
          sudo apt update
          chmod +x ./get_elasticsearch.sh
          ./get_elasticsearch.sh