name: build zxing android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Build ZXing Android
        run: |
          chmod +x java/zxing/android/latest/build.sh
          java/zxing/android/latest/build.sh
